In [1]:
%autosave 0

Autosave disabled


Numpy makes it easy for us to work with large amounts of numerical data in arrays. Many other libraries (including Pandas) are built on Numpy. It's important to be familiar working with this library in order to understand the functionality of the other libraries.

In [2]:
#standard import
import numpy as np

We create Numpy arrays with the np.array function. Inside the function, we can pass a list as the argument.

In [3]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

We can index a Numpy array, much like a list!

In [4]:
array[0]

1

In [5]:
array[2:]

array([3, 4, 5])

In [6]:
array[-3:]

array([3, 4, 5])

In [7]:
array[:-3]

array([1, 2])

Vectorized operations allow us to perform a mathematical operation on EVERY number in an array.

Let's compare how we could do the same thing with a list and a Numpy array.

In [8]:
array * 10

array([10, 20, 30, 40, 50])

In [9]:
my_list = [1, 2, 3, 4, 5]

In [11]:
empty_list = []

for num in my_list:
    empty_list.append(num * 10)
    
empty_list    

[10, 20, 30, 40, 50]

Boolean masking is an important concept we will apply consistently with Pandas. We will get back an array filled with Boolean values, and use it to MASK (hide or remove) certain values from the output.

In [13]:
mask = array > 3
mask

array([False, False, False,  True,  True])

In [14]:
array[mask]

array([4, 5])

In [15]:
array[array < 3]

array([1, 2])

We can create arrays from the standard normal distribution (mean of 0, standard deviation of 1) using np.random.randn. We specify the shape of the resulting array as the argument for the function.

In [17]:
st_norm = np.random.randn(5)
st_norm

array([-0.24357555,  0.42306243, -1.94105849, -1.97597695, -1.31317973])

In [19]:
np.random.randn(3, 3, 3)

array([[[ 0.21419761, -1.29422271,  1.17469201],
        [-0.64640463,  1.10055438,  1.06779205],
        [ 0.15591789, -2.27571454,  2.06506956]],

       [[-0.25082551, -1.10813548, -0.81841777],
        [-1.69939149, -1.5780714 , -1.61287096],
        [ 1.17590383,  1.11804288, -0.47721686]],

       [[ 0.41183146,  0.04486096, -2.22437225],
        [ 2.25973955,  0.78370961,  0.69829727],
        [ 0.66961937, -1.36022103,  0.29854539]]])

We can create arrays from other normal distributions using np.random.normal. To this function, we will pass in arguments specifying the mean, the standard deviation, and the size of the resulting array.

In [20]:
my_norm = np.random.normal(30, 5, 5)
my_norm

array([28.44580238, 25.96020815, 27.53239513, 25.77701262, 34.05984775])

We can create arrays from a range using np.arange. We specify the starting value, the stopping value, and the step size.

In [21]:
range_array = np.arange(0, 12, 3)
range_array

array([0, 3, 6, 9])

We can call a number of array methods to return descriptive statistics, such as min, max, mean, standard deviation, and sum.

In [22]:
range_array.sum()

18

In [23]:
range_array.mean()

4.5

In [24]:
range_array.max()

9